#!/bin/bash

set -e

if ! test -d htmlcov
then
    echo "Generate coverage first by running: python setup.py pytest"
    exit 1
fi

sphinx-build -W -b html sphinx sphinx/generated | sed 's:sphinx/generated:./html:'
test $PIPESTATUS == 0
mv sphinx/generated html
cp -R htmlcov html/cover
